/**
 * Represents a NFT historic event type.
 */
export enum NftHistoricEventType {
  LOAN_REQUEST_CREATED = "LOAN_REQUEST_CREATED",
  LOAN_REQUEST_CANCELLED = "LOAN_REQUEST_CANCELLED",
  LOAN_FUNDED = "LOAN_FUNDED",
  LOAN_REPAID = "LOAN_REPAID",
  DELINQUENT_NFT_CLAIMED = "DELINQUENT_NFT_CLAIMED",
  NFT_MINTED = "NFT_MINTED",
  NFT_TRANSFERRED = "NFT_TRANSFERRED",
}
